server.port=8081

spring.datasource.url=jdbc:mysql://mysql-flight:3306/flightdb
spring.datasource.username=flight
spring.datasource.password=flight

eureka.instance.prefer-ip-address=true

spring.activemq.broker-url=tcp://activemq:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.activemq.packages.trust-all=true
spring.jms.pub-sub-domain=false

flight.source=DOCKER_ENV
management.endpoints.web.exposure.include=*
