server.port=8084
aws.ses.region=ap-south-1
aws.ses.sender=noreply@airline.com
notification.retry.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/notification_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
aws.region=ap-south-1
aws.ses.from=1729222@gmail.com
template.service.url=http://localhost:9090
management.endpoints.web.exposure.include=*
