server.port=8084
aws.ses.region=ap-south-2
notification.retry.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/notification_db
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
aws.ses.from=sindhumohanty34@gmail.com
aws.accessKey=AKIASLLC32GB6TTN5JCB
aws.secretKey=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
template.service.url=http://localhost:9090
management.endpoints.web.exposure.include=*
