# -----------------------------
# Server & Management
# -----------------------------
server.port=9098
management.endpoints.web.exposure.include=*

# -----------------------------
# Eureka
# -----------------------------
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# -----------------------------
# Datasource (Docker MySQL container)
# -----------------------------
spring.datasource.url=jdbc:mysql://passenger-db:3306/passengerdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.batch.jdbc.initialize-schema=never
spring.sql.init.mode=always
spring.batch.job.enabled=true

# -----------------------------
# External Services (fixed URLs, not registered in Eureka)
# -----------------------------
passenger.resibernetUrl=http://resibernet-service:9092/resibernet
passenger.amadeusUrl=http://amadeus-service:9092/amadeus

# -----------------------------
# Resilience4j Circuit Breaker
# -----------------------------
resilience4j.circuitbreaker.instances.passengerService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.passengerService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.passengerService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.passengerService.waitDurationInOpenState=10s

# -----------------------------
# Resilience4j Retry
# -----------------------------
resilience4j.retry.instances.passengerService.maxAttempts=3
resilience4j.retry.instances.passengerService.waitDuration=1s

# -----------------------------
# JWT
# -----------------------------
jwt.secret=hP1lL2e3vH9aDqYxFq3kG2uV1Jm+9t7rX0yQp1Sx2Zo=
