spring.datasource.url=jdbc:mysql://passenger-db:3306/passengerdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=*
server.port=9098

# External services (fixed URLs)
passenger.resibernetUrl=http://resibernet-service:9092/resibernet
passenger.amadeusUrl=http://amadeus-service:9092/amadeus

spring.batch.jdbc.initialize-schema=never
spring.sql.init.mode=always
spring.batch.job.enabled=true
