spring.datasource.url=jdbc:mysql://passenger-db:3306/passengerdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=*
server.port=9099
# External services (fixed URLs)
passenger.amadeusUrl=http://externalapis:9094/amadeus
passenger.resibernetUrl=http://externalapis:9094/resibernet
spring.batch.jdbc.initialize-schema=never
spring.sql.init.mode=always
spring.batch.job.enabled=true
