spring.datasource.url=jdbc:mysql://localhost:3306/passengerdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=*
server.port=8082
passenger.resibernetUrl=http://localhost:9092/resibernet
passenger.amadeusUrl=http://localhost:9092/amadeus
